### ISSUE TITLE
Gibberish On-Screen Text

### ISSUE THREAD

**Issue by wjk** [insidegui/AppearanceMaker#2]
I was trying to create an `NSAppearance` with your app on OS X 10.10, but when I opened it, I got this. (Apologies for the overlarge image, by the way.)

![Gibberish Screenshot](https://cloud.githubusercontent.com/assets/1915951/5641469/634fc324-9607-11e4-8064-ba1f5eca543c.png)

I am running the prebuilt version of AppearanceMaker on OS X 10.10.1. I have tried deleting and reinstalling the app, and clearing the preferences using `defaults delete`. Nothing has worked. Any pointers?

**Comment by wjk** [comment]
Update: Commenting out [AMEditorWC.m line 75](https://github.com/insidegui/AppearanceMaker/blob/master/Appearance%20Maker/Controllers/AMEditorWC.m#L75) and recompiling fixes the problem. However, this “fix” doesn’t inspire confidence that the theme files your app creates will work on OS X 10.10.

**Comment by insidegui** [comment]
Unfortunately AppearanceMaker is not working well in Yosemite :(

**Comment by wjk** [comment]
That’s a shame; I really like the concept of what this project might have been able to do. Any thoughts why?

**Comment by insidegui** [comment]
From what I've been able to tell, Apple is not using the same API to draw the controls, making this project somewhat obsolete. That's a risk you take when using private APIs...

**Comment by wjk** [comment]
Oh well. It was fun while it lasted. Thanks anyways.
