### ISSUE TITLE
Exported appearance makes app lock up

### ISSUE THREAD

**Issue by DagAgren** [insidegui/AppearanceMaker#4]
I attempted to create a test appearance with this app, by exporting one set of images and editing one, and then exporting. This created a .car file that when included and loaded in another app, causes the app to deadlock in the NSWindowDrawing code (in NSSystemDynamicColor set, I think it was).

Any idea what might be going on here? Is it supposed to work in its current state?

**Comment by insidegui** [comment]
Setting the appearance for the entire window is not working, I would set the custom appearance only for the contentView of the window or only for specific UI elements and customize the window with code.

**Comment by DagAgren** [comment]
The problem is, in 10.10 you get warnings when trying to add views outside the contentView, and in 10.11 doing so seems to trigger bugs. So there no longer is a way to customise the window from code other than NSAppearance, which is why I've been trying to use AppearanceMaker.

Any idea why it doesn't work, and if there might be some way to get it working? Or is NSAppearance just not finished enough yet?

**Comment by insidegui** [comment]
It is possible to customize the window without adding subviews to the theme frame.

It doesn't work because the underlying APIs are changing very rapidly (in 10.10 they didn't work at all) and not every element of the UI uses these APIs to draw.

**Comment by DagAgren** [comment]
It seems to be trying to use it, though, since it locks up when you supply an appearance. But I guess we'll have to wait for it to stabilise a bit more.

I haven't found any way to change window appearance though that doesn't involve creating your own replacement titlebar, and that's not a path I want to go down. Implementing all the subtle little behaviours correctly is nearly impossible.

**Comment by insidegui** [comment]
It's not that bad, I'm implementing this for a new version of GRProKit. [Here's the code](https://dl.dropboxusercontent.com/u/452482/stackoverflow/GRProWindow.zip) if you want to take a look at how I'm doing It.

**Comment by DagAgren** [comment]
Interesting. I did try it a bit but turning on the full content view mode seems to interfere with my OpenGL drawing somehow so I may have to leave it for later.

Is there a reason you dig out the visualeffectsview there? It doesn't seem necessary, at first glace.

**Comment by insidegui** [comment]
Yes It is, I add my custom titlebar as a subview of the original titlebar.

**Comment by DagAgren** [comment]
All right.

I wonder if the default appearances have .car files living anywhere? Have you tried looking?

**Comment by insidegui** [comment]
The default controls are inside CoreUI's ArtFile, but dark mode, vibrancy and other effects have .car files in `/System/Library/CoreServices/SystemAppearance.bundle`, but they don't have assets (images), only effects.
