### ISSUE TITLE
App is hard to understand how to use

### ISSUE THREAD

**Issue by DagAgren** [insidegui/AppearanceMaker#5]
I'm not sure I'm managing to use this app correctly at all. I can select things, and export them to be customised, but after this nothing in particular happens. If I change a file, it doesn't change in the lists in the program, and there's no way to explicitly import things back, so it's a bit impossible to figure out what is going on.

**Comment by insidegui** [comment]
The app is not finished yet, there's a lot of functionality missing.

**Comment by DagAgren** [comment]
Is it supposed to be possible to make working themes with it, though?

**Comment by insidegui** [comment]
Yes. Just look at the app itself, It uses a custom theme to change the colors of the buttons and popups. Just be aware that this doesn't work in 10.10 (as stated in the readme).

**Comment by DagAgren** [comment]
All right. Maybe you should add a few lines to the readme that describe the workflow?
